package com.abc.Jwt;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
// it is used to generate object of nested static builder class which is generated by this @Builder
// annotation itself and it has .build() to wrap total code

public class JwtToken {
    private String accessToken;
}
